### ISSUE TITLE
Mesmo o funcionário não sendo responsável pela OS ele pode apagá-la

### ISSUE THREAD

**Issue by majupeixoto** [majupeixoto/vitu_projeto#12]
![Captura de tela 2024-05-21 113821](https://github.com/lua-mf/vitu_projeto/assets/143026488/c38ef870-8dca-490a-aafd-087e4fde8c21)

**Comment by paulo-rago** [comment]
fechado em: 3fd05a2758cf2a1489af3be50d3982e8e3605e6d
