### ISSUE TITLE
Página de erro ao logar maju / 123 em Funcionário

### ISSUE THREAD

**Issue by dekenner** [majupeixoto/vitu_projeto#17]
![Captura de tela 2024-05-26 205153](https://github.com/lua-mf/vitu_projeto/assets/149336406/abf1f153-5e76-410f-b182-18b8407e1bc0)
![Captura de tela 2024-05-26 205134](https://github.com/lua-mf/vitu_projeto/assets/149336406/cf15e61e-e53d-4d6c-baf0-23948833b700)

**Comment by paulo-rago** [comment]
fechado aqui: f213e4bb10ddcbb7a261b987bc8b281225546fe2
