### ISSUE TITLE
Ao inserir uma informação inválida, vai para página de erro

### ISSUE THREAD

**Issue by majupeixoto** [majupeixoto/vitu_projeto#18]
é bom refinar o sistema de verificação
![image](https://github.com/lua-mf/vitu_projeto/assets/143026488/977d3b2e-c5f8-4f9d-9ad8-e44fc5abb709)

**Comment by paulo-rago** [comment]
fechado aqui: f213e4bb10ddcbb7a261b987bc8b281225546fe2

**Comment by paulo-rago** [comment]
fechei a issue errada kkkkk

**Comment by majupeixoto** [comment]
fechada no commit: 51065ca9f70e3ca9ed698dcb07979612fdda8d23
